### ISSUE TITLE
Must I use "<!-- -->" to lazyload something? 

### ISSUE THREAD

**Issue by NexusLee** [emn178/jquery-lazyload-any#13]
Why dont use "data-original" attr like jquery lazyload. It may be in conflict.

**Comment by emn178** [comment]
Hi Lee,

jquery-lazyload is for image only. data-original will replace img src without doubt.
This plugin could be for anything, so the easiest way it to use comment.
If you use for image only, jquery-lazyload could be fit to your need.

**Comment by NexusLee** [comment]
@emn178  Thanks,  I want to load iframe lazily. I used jquery-lazyload-any, but it's conflict with something. So I use another plugin.  Thanks anyway.

**Comment by emn178** [comment]
805063c added new styles for this requirement.

**Comment by NexusLee** [comment]
👍
