### ISSUE TITLE
Not working on firefox

### ISSUE THREAD

**Issue by Rapheer** [emn178/jquery-lazyload-any#14]
I'm trying to use lazyload to load a doubleclick ad but it doesn't work on Firefox and IE, only in chrome.

this is my doubleclick container
![capturar](https://cloud.githubusercontent.com/assets/5366508/9063307/24035d4e-3a9d-11e5-8f9d-aea1150bfff6.PNG)

this is the lazyload initializing code
![capturar2](https://cloud.githubusercontent.com/assets/5366508/9063315/28e91d9e-3a9d-11e5-83f9-03f79cba1023.PNG)

this is the code on chrome
![capturar3](https://cloud.githubusercontent.com/assets/5366508/9063319/2beacad8-3a9d-11e5-85d2-9c931f7502c8.PNG)

this is the code on Firefox or IE
![capturar4](https://cloud.githubusercontent.com/assets/5366508/9063321/2e58e836-3a9d-11e5-82a3-3b75f16086a9.PNG)

I have no idea of what's happening

**Comment by emn178** [comment]
Did you check this?
https://github.com/emn178/jquery-lazyload-any#notice

**Comment by emn178** [comment]
Do you fix it?
