### ISSUE TITLE
ie8 FF inserting-a-comment-in-innerhtml error

### ISSUE THREAD

**Issue by hyingzi** [emn178/jquery-lazyload-any#17]
http://stackoverflow.com/questions/15006001/inserting-a-comment-in-innerhtml

**Comment by emn178** [comment]
sorry, I don't understand.

**Comment by hyingzi** [comment]
刚看到您是台湾的，那我打中文。。。英文不好～
因为插件是抓取注释里的图片激活加载的，如下
```html
<div class="lazyload">
  <!--
    <img src="image.png" />
  -->
</div>
```
在有些场景（ajax、模板等）使用中，需要动态的去插入这些代码，如
```javascript
var tpl = '<div class="lazyload"><!--<img src="image.png" />--></div>'

// 写入
document.getElementsByTagName("body")[0].innerHTML = tpl
$(".lazyload").lazyload()
```
这个的时候，在ie8或者某些firefox版本中，写入的其实是
```
<div class="lazyload"></div>
```
也就是说，注释里的内容被过滤掉了……

还有一种情况，网站如果使用cdn的并且开启代码优化的话，注视也会被过滤掉…

所以，注释这种的方式好像不是很安全

**Comment by emn178** [comment]
Hi,

感謝你的建議, 未來將考慮增加其他的方式改善這個問題, 可能的方式是用屬性實現

**Comment by emn178** [comment]
Hi, 805063c 新增兩種使用方式可解決此問題

**Comment by hyingzi** [comment]
非常感谢！
