### ISSUE TITLE
How to retain scroll position when redirected back to the page?

### ISSUE THREAD

**Issue by digimid** [emn178/jquery-lazyload-any#18]
Hello there,

I really like your plugin and easy usability it provides. I have to make this plugin better by retaining the scroll postilion once we press back from the browser and land back to the listing with the lazyload after we have viewed one of the records from it.

What i have brainstormed as far is on unload of the window when a record is clicked, i save the scroll position in local storage and then when i redirect back i check for the scroll position existence in local storage and remap the position according to the value. But as this page has lazyload the section is hidden and it doesnt open up. I want to disable the lazyload in this case. Is there any way i could achieve this with this plugin?

I will greatly appreciate your opinion.
Thanks alot

**Comment by emn178** [comment]
Hi,

If the lazyload elements specified height and not loaded by AJAX, it could retain scroll position after history back.
Like this demo: http://emn178.github.io/jquery-lazyload-any/samples/images/
What's your scenario?

**Comment by digimid** [comment]
hello,

I am actually loading content via lazyload, so when i press back only the initial placeholder shows , and everything else is hidden. can you just tell me is there any way i could disable lazyload on history back button, so the whole content loads?

Thanks

**Comment by emn178** [comment]
You want to disable lazyload after users click history back. jQuery-lazyload-any does not provide this feature. I think that the solution should be not to initialize lazyload if it's matched your case.
```JavaScript
if (!your_case) {
  $('.lazyload').lazyload();
}
```
So the problem is how to detect your_case.
In your case, it means how to detect if it's a history page.
And I found this: http://stackoverflow.com/questions/28773062/detect-if-the-user-arrived-to-the-current-page-via-the-browser-back-button

**Comment by digimid** [comment]
yes i have figured it out till here, but i have lazyload content in comments (<!-->) , so it still doesn't show the content. should i use some other approach like script or attribute style for the content?

**Comment by digimid** [comment]
Via JS i got the comments removed and now its working perfectly. Thank you for all your time and effort, i really appreciate it.

Happy Coding to you!
