### ISSUE TITLE
Trying to combine Isotope with Lazyload

### ISSUE THREAD

**Issue by johndrach** [emn178/jquery-lazyload-any#21]
I am working on a project where I am using Isotope to search and filter blocks of content on a page similar to what is here(https://codepen.io/desandro/pen/wfaGu). The page is very image heavy so I was hoping to leverage your plugin to lazy load the content. The issue I run into is when I perform a search in order to filter and the content is brought to the top of the page the content is still commented out. If I scroll down to the content which I am commenting out it works just fine. Is there a simple fix for this where you can point me in the right direction?

**Comment by emn178** [comment]
hi, please refer [this](https://github.com/emn178/jquery-lazyload-any#notice).
try to call `$.lazyload.check()` after searching.
