### ISSUE TITLE
Need Help: How can I make a lazyload for div contents text?

### ISSUE THREAD

**Issue by chhumsina** [emn178/jquery-lazyload-any#9]
Dear Mr. or Miss,
I am interested in  your plugin, and currently I use this awesome plugin. 
I would like to know how to make a lazyload for div contents text as the example code above (I don't now how to use in this plugin for text). Could you guide how to produce?
This code image just my imagine idea.

![capture](https://cloud.githubusercontent.com/assets/3894767/4793857/f4eef2ea-5df0-11e4-96e9-941ff2ad14cb.PNG)

Raw code: http://notepad.cc/fleruky33
Thanks you :)

**Comment by katwer** [comment]
Thanks a lot @emn178 for lazyload-any and for this tips, it resolve my problem today!

**Comment by me-harmeek** [comment]
http://jquery.eisbehr.de/lazy/
